# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pypslite/pslite.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pypslite/pslite.proto\x12\rpslite_protos\"\x0e\n\x0c\x45mptyMessage\"?\n\x05Topic\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0crecords_path\x18\x02 \x01(\t\x12\x12\n\nindex_path\x18\x03 \x01(\t\"7\n\x10OpenTopicRequest\x12#\n\x05topic\x18\x01 \x01(\x0b\x32\x14.pslite_protos.Topic\"b\n\x0ePublishRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x17\n\rcontent_bytes\x18\x02 \x01(\x0cH\x00\x12\x18\n\x0e\x63ontent_string\x18\x03 \x01(\tH\x00\x42\t\n\x07\x63ontent\"J\n\x10SubscribeRequest\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x12\n\nend_offset\x18\x03 \x01(\x03\":\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0e\n\x06length\x18\x03 \x01(\x03\x32\xe9\x01\n\rPSLiteService\x12I\n\tOpenTopic\x12\x1f.pslite_protos.OpenTopicRequest\x1a\x1b.pslite_protos.EmptyMessage\x12\x45\n\x07Publish\x12\x1d.pslite_protos.PublishRequest\x1a\x1b.pslite_protos.EmptyMessage\x12\x46\n\tSubscribe\x12\x1f.pslite_protos.SubscribeRequest\x1a\x16.pslite_protos.Message0\x01\x42\x1aZ\x18github.com/panyam/psliteb\x06proto3')



_EMPTYMESSAGE = DESCRIPTOR.message_types_by_name['EmptyMessage']
_TOPIC = DESCRIPTOR.message_types_by_name['Topic']
_OPENTOPICREQUEST = DESCRIPTOR.message_types_by_name['OpenTopicRequest']
_PUBLISHREQUEST = DESCRIPTOR.message_types_by_name['PublishRequest']
_SUBSCRIBEREQUEST = DESCRIPTOR.message_types_by_name['SubscribeRequest']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'pypslite.pslite_pb2'
  # @@protoc_insertion_point(class_scope:pslite_protos.EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

Topic = _reflection.GeneratedProtocolMessageType('Topic', (_message.Message,), {
  'DESCRIPTOR' : _TOPIC,
  '__module__' : 'pypslite.pslite_pb2'
  # @@protoc_insertion_point(class_scope:pslite_protos.Topic)
  })
_sym_db.RegisterMessage(Topic)

OpenTopicRequest = _reflection.GeneratedProtocolMessageType('OpenTopicRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPENTOPICREQUEST,
  '__module__' : 'pypslite.pslite_pb2'
  # @@protoc_insertion_point(class_scope:pslite_protos.OpenTopicRequest)
  })
_sym_db.RegisterMessage(OpenTopicRequest)

PublishRequest = _reflection.GeneratedProtocolMessageType('PublishRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHREQUEST,
  '__module__' : 'pypslite.pslite_pb2'
  # @@protoc_insertion_point(class_scope:pslite_protos.PublishRequest)
  })
_sym_db.RegisterMessage(PublishRequest)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'pypslite.pslite_pb2'
  # @@protoc_insertion_point(class_scope:pslite_protos.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'pypslite.pslite_pb2'
  # @@protoc_insertion_point(class_scope:pslite_protos.Message)
  })
_sym_db.RegisterMessage(Message)

_PSLITESERVICE = DESCRIPTOR.services_by_name['PSLiteService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\030github.com/panyam/pslite'
  _EMPTYMESSAGE._serialized_start=40
  _EMPTYMESSAGE._serialized_end=54
  _TOPIC._serialized_start=56
  _TOPIC._serialized_end=119
  _OPENTOPICREQUEST._serialized_start=121
  _OPENTOPICREQUEST._serialized_end=176
  _PUBLISHREQUEST._serialized_start=178
  _PUBLISHREQUEST._serialized_end=276
  _SUBSCRIBEREQUEST._serialized_start=278
  _SUBSCRIBEREQUEST._serialized_end=352
  _MESSAGE._serialized_start=354
  _MESSAGE._serialized_end=412
  _PSLITESERVICE._serialized_start=415
  _PSLITESERVICE._serialized_end=648
# @@protoc_insertion_point(module_scope)
